package com.sn1persecurity.silentchain.bapp.scan;

import burp.api.montoya.http.message.HttpRequestResponse;
import burp.api.montoya.scanner.audit.issues.AuditIssue;
import burp.api.montoya.scanner.audit.issues.AuditIssueConfidence;
import burp.api.montoya.scanner.audit.issues.AuditIssueSeverity;

import com.sn1persecurity.silentchain.bapp.SilentchainExtension;
import com.sn1persecurity.silentchain.bapp.ai.ParsedFinding;

public final class FindingBuilder {

    private FindingBuilder() {}

    public static AuditIssue build(ParsedFinding finding, HttpRequestResponse rr) {
        String baseUrl = (rr.request() != null) ? rr.request().url() : "";
        AuditIssueSeverity severity = mapSeverity(finding.severityRaw());
        AuditIssueConfidence confidence = mapConfidence(finding.confidence());

        String name = "SILENTCHAIN: " + finding.title();
        String detail = buildDetailHtml(finding);
        String remediation = escapeHtml(finding.remediation());
        String background = buildBackground(finding);

        return AuditIssue.auditIssue(
                name,
                detail,
                remediation,
                baseUrl,
                severity,
                confidence,
                background,
                "Address the issue at its root cause as described in the remediation guidance.",
                severity,
                rr
        );
    }

    private static String buildDetailHtml(ParsedFinding f) {
        StringBuilder sb = new StringBuilder();
        sb.append("<p>").append(escapeHtml(f.detail())).append("</p>");

        sb.append("<ul>");
        if (!f.owasp().code().isEmpty()) {
            sb.append("<li><b>OWASP:</b> ").append(escapeHtml(f.owasp().code()))
              .append(" &mdash; ").append(escapeHtml(f.owasp().displayName())).append("</li>");
        }
        f.normalizedCwe().ifPresent(cwe ->
                sb.append("<li><b>CWE:</b> ").append(escapeHtml(cwe)).append("</li>")
        );
        sb.append("<li><b>AI confidence:</b> ").append(f.confidence()).append("%</li>");
        sb.append("</ul>");

        if (!f.evidence().isBlank()) {
            sb.append("<p><b>Evidence:</b></p><pre>")
              .append(escapeHtml(f.evidence()))
              .append("</pre>");
        }

        sb.append("<p><i>Want active verification with exploit payloads, WAF evasion, ")
          .append("and out-of-band testing? See <a href=\"https://silentchain.ai\">SILENTCHAIN Pro</a>.</i></p>");

        // Legal disclaimer — present at the bottom of every SILENTCHAIN finding.
        // (Burp's issue-advisory HTML renderer does not support <hr>.)
        sb.append("<p><i>Generated by SILENTCHAIN Community Edition v")
          .append(SilentchainExtension.EXTENSION_VERSION)
          .append(". SILENTCHAIN is owned by Sn1perSecurity LLC. SILENTCHAIN is an independent product and is ")
          .append("not affiliated with, endorsed by, or sponsored by PortSwigger Ltd. or Burp Suite in any way. ")
          .append("&quot;Burp Suite&quot; and &quot;Burp&quot; are trademarks of PortSwigger Ltd., used for ")
          .append("nominative descriptive purposes only.</i></p>");
        return sb.toString();
    }

    private static String buildBackground(ParsedFinding f) {
        if (f.owasp().code().isEmpty()) {
            return "AI-assisted finding generated by SILENTCHAIN Community Edition.";
        }
        return "Maps to " + escapeHtml(f.owasp().code()) + " ("
                + escapeHtml(f.owasp().displayName())
                + "). Identified via AI analysis of the captured HTTP exchange.";
    }

    private static AuditIssueSeverity mapSeverity(String raw) {
        if (raw == null) {
            return AuditIssueSeverity.INFORMATION;
        }
        return switch (raw.trim().toLowerCase()) {
            case "high", "critical" -> AuditIssueSeverity.HIGH;
            case "medium" -> AuditIssueSeverity.MEDIUM;
            case "low" -> AuditIssueSeverity.LOW;
            default -> AuditIssueSeverity.INFORMATION;
        };
    }

    /**
     * Confidence mapping ported from Community map_confidence()
     * (silentchain_ai_community.py:252).
     */
    static AuditIssueConfidence mapConfidence(int aiConfidence) {
        if (aiConfidence < 75) {
            return AuditIssueConfidence.TENTATIVE;
        }
        if (aiConfidence < 90) {
            return AuditIssueConfidence.FIRM;
        }
        return AuditIssueConfidence.CERTAIN;
    }

    private static String escapeHtml(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
